<?php

/**
 * @file
 * Contains installation and uninstallation procedurs for siteapikey.
 */

/**
 * Implements hook_install().
 */
function siteapikey_install() {
  drupal_set_message(t('Please !click here to set a Site API Key.',
    array(
      '!click' => l(t('Click Here'), 'admin/config/system/site-information')
    )
  ));
}

/**
 * Implements hook_uninstall().
 */
function siteapikey_uninstall() {
  variable_del('siteapikey');
}
