<?php

/**
 * @file
 * Contains complex business logic for siteapikey module.
 */

/**
 * Implements hook_form_FORM_ID_alter().
 */
function siteapikey_form_system_site_information_settings_alter(&$form, &$form_state, $form_id) {
  // Adding a fieldset for our textfield.
  $form['siteapikey_fieldset'] = array(
    '#type' => 'fieldset',
    '#title' => t('Site API Key'), 
    '#weight' => 5, 
    '#collapsible' => FALSE,
  );
  // Adding the siteapikey textfield.
  $form['siteapikey_fieldset']['siteapikey'] = array(
    '#type' => 'textfield',
    '#title' => t('Site API Key'), 
    '#default_value' => variable_get('siteapikey', t('No API Key yet')),
    '#required' => TRUE,
  );

  // Check if the variable is set, if yes change our submit button name.
}

/**
 * Implements hook_menu().
 */
function